version: '3.8'

services:
  cache:
    container_name: redis-cache
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --requirepass "lfjdop23oipfghdsa"
    volumes:
      - .docker/redis-data:/data
  goapp:
    build: .
    container_name: go-ratelimiter
    ports:
      - 8080:8080
    environment:
      - APP_ENV=production
    depends_on:
      - cache
  ip-tests:
    container_name: ip-tests
    image: jordi/ab
    command: -n 20 -v 3 -H 'X-Real-Ip:123.123.123' http://goapp:8080/ 
    depends_on:
      - goapp
  token-tests:
    container_name: token-tests
    image: jordi/ab
    command: -n 20 -v 3 -H 'Api-Key:token-abc' http://goapp:8080/ 
    depends_on:
      - goapp

    